HAPROXY_VERSION="3.4.6"
HAPROXY_SHA256SUM="791e1815f8af6e8b850a227a9a0a190f3d3478c9e8d38a0f51c98b7f4bfe368b"

getpkg http://www.haproxy.org/download/${HAPROXY_VERSION%.*}/src/haproxy-${HAPROXY_VERSION}.tar.gz $HAPROXY_SHA256SUM
tar zxf haproxy-${HAPROXY_VERSION}.tar.gz
cd haproxy-${HAPROXY_VERSION}

OPTS="USE_PCRE2=1 USE_OPENSSL=1 USE_ZLIB=1 PREFIX= DESTDIR=$VENV"
if [ "$MOS" == "MacOS" ]; then
  OPTS="TARGET=osx $OPTS SSL_INC=$BREW_PREFIX/include SSL_LIB=$BREW_PREFIX/lib"
else
  OPTS="TARGET=linux-glibc $OPTS"
fi

$PMAKE $OPTS
$PMAKE $OPTS install
